name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - "crates/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - 'crates/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --workspace --all-features

  # clippy-lints:
  #   name: Clippy lints
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dtolnay/rust-toolchain@nightly
  #       with:
  #         components: clippy
  #     - uses: Swatinem/rust-cache@v2
  #     - name: Run lints
  #       env:
  #         RUSTFLAGS: -C debuginfo=0
  #       run: |
  #         cargo clippy --all-features
  #         cargo clippy -- -D warnings

  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Run formatting check
        run: |
          cargo fmt --all -- --check
